### ISSUE TITLE
Viewing "Indexes" tab is broken with Zope 4 / ZCatalog 5.0.1

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.ZCatalog#84]
With 5.0.1 ( see #75 and #62 converted ) manage_catalogIndexes was converted from DTML to TAL.

Since then I cannot view the Indexes tab for any Catalog in my Zope 4 app.

I get this traceback:

```
2019-11-07 16:22:29,520 ERROR   [Zope.SiteErrorLog:251][waitress] 1573140149.520.776789468942 http://localhost:8084/bliss/data/Addresses/Catalog/manage_catalogIndexes
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.PageTemplates.PageTemplateFile, line 145, in _exec
  Module Products.PageTemplates.PageTemplate, line 85, in pt_render
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module zope.pagetemplate.pagetemplate, line 265, in __call__
  Module zope.tal.talinterpreter, line 272, in __call__
  Module zope.tal.talinterpreter, line 344, in interpret
  Module zope.tal.talinterpreter, line 534, in do_optTag_tal
  Module zope.tal.talinterpreter, line 519, in do_optTag
  Module zope.tal.talinterpreter, line 514, in no_tag
  Module zope.tal.talinterpreter, line 344, in interpret
  Module zope.tal.talinterpreter, line 587, in do_setLocal_tal
  Module zope.tales.tales, line 775, in evaluate
   - URL: manage_catalogIndexes
   - Line 15, Column 2
   - Expression: <PythonExpr sorted(indexes.filtered_meta_types(), key=lambda mt: mt['name'])>
   - Names:
      {'container': <ZCatalog at /bliss/data/Addresses/Catalog>,
       'context': <ZCatalog at /bliss/data/Addresses/Catalog>,
       'default': <object object at 0x7f039565c770>,
       'here': <ZCatalog at /bliss/data/Addresses/Catalog>,
       'loop': {},
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f035fa79a70>,
       'request': <WSGIRequest, URL=http://localhost:8084/bliss/data/Addresses/Catalog/manage_catalogIndexes>,
       'root': <Application at >,
       'template': <PageTemplateFile at /bliss/data/Addresses/Catalog/catalogIndexes>,
       'user': <User 'admin'>}
  Module Products.PageTemplates.ZRPythonExpr, line 49, in __call__
   - __traceback_info__: sorted(indexes.filtered_meta_types(), key=lambda mt: mt['name'])
  Module PythonExpr, line 1, in <module>
NameError: name 'sorted' is not defined
^C/home/jugmac00/Projects/bliss_deployment/work/_/home/jugmac00/.batou-shared-eggs/waitress-1.3.0-py2.7.egg/waitress/wasyncore.py:617: UserWarning: unclosed file <waitress.wasyncore.file_wrapper instance at 0x7f0376760170>
  warnings.warn("unclosed file %r" % self, compat.ResourceWarning)
```

There is no issue with ZCatalog 5.0

**Update**
- template seems to be a working chameleon template
- template is broken when I use pagetemplate (which is what my app uses)

**Reproduction**
- vanilla Zope installation
- deactivate Chameleon / turn on "oldstyle page templates" by e.g. commenting `  <!--<utility component=".engine.Program" />-->` within the configure.zcml of PageTemplates
- create catalog
- go to index tag
- crash

```
2019-11-08 08:51:15 ERROR [waitress:363][waitress] Exception while serving /some_catalog/manage_catalogIndexes
Traceback (most recent call last):
  File "/home/jugmac00/Tests/Zope/eggs/waitress-1.3.1-py3.6.egg/waitress/channel.py", line 356, in service
    task.service()
  File "/home/jugmac00/Tests/Zope/eggs/waitress-1.3.1-py3.6.egg/waitress/task.py", line 172, in service
    self.execute()
  File "/home/jugmac00/Tests/Zope/eggs/waitress-1.3.1-py3.6.egg/waitress/task.py", line 440, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/home/jugmac00/Tests/Zope/src/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/jugmac00/Tests/Zope/eggs/Paste-3.1.1-py3.6.egg/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/jugmac00/Tests/Zope/src/ZPublisher/WSGIPublisher.py", line 333, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/jugmac00/Tests/Zope/src/ZPublisher/WSGIPublisher.py", line 251, in publish
    bind=1)
  File "/home/jugmac00/Tests/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/jugmac00/Tests/Zope/src/ZPublisher/WSGIPublisher.py", line 57, in call_object
    return obj(*args)
  File "/home/jugmac00/Tests/Zope/src/Shared/DC/Scripts/Bindings.py", line 335, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/jugmac00/Tests/Zope/src/Shared/DC/Scripts/Bindings.py", line 372, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/jugmac00/Tests/Zope/src/Products/PageTemplates/PageTemplateFile.py", line 145, in _exec
    return self.pt_render(extra_context=bound_names)
  File "/home/jugmac00/Tests/Zope/src/Products/PageTemplates/PageTemplate.py", line 85, in pt_render
    showtal=showtal)
  File "/home/jugmac00/Tests/Zope/eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/jugmac00/Tests/Zope/eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 265, in __call__
    interpreter()
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 272, in __call__
    self.interpret(self.program)
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 344, in interpret
    handlers[opcode](self, args)
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 534, in do_optTag_tal
    self.do_optTag(stuff)
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 519, in do_optTag
    return self.no_tag(start, program)
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 514, in no_tag
    self.interpret(program)
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 344, in interpret
    handlers[opcode](self, args)
  File "/home/jugmac00/Tests/Zope/eggs/zope.tal-4.4-py3.6.egg/zope/tal/talinterpreter.py", line 587, in do_setLocal_tal
    self.engine.setLocal(name, self.engine.evaluateValue(expr))
  File "/home/jugmac00/Tests/Zope/eggs/zope.tales-5.0.1-py3.6.egg/zope/tales/tales.py", line 775, in evaluate
    return expression(self)
  File "/home/jugmac00/Tests/Zope/src/Products/PageTemplates/ZRPythonExpr.py", line 49, in __call__
    return eval(self._code, vars, {})
  File "PythonExpr", line 1, in <module>
NameError: name 'sorted' is not defined
```

**Comment by jugmac00** [comment]
If anybody else has the same problem - as an intermediary fix I pinned ZCatalog to 5.0 via buildout.
